package br.edu.uepb.sigeris.enumerations;

import java.io.Serializable;

/**
 *
 * @author cassio
 */
public enum GruposUsuarios implements Serializable {

	CPD,
    DIRECAO,
    EXTENSAO,
    SECLETRAS,
    BIBLIOTECA,
    PROFESSORES,
    SECCONTABEIS,
    SECMATEMATICA,
    TERCEIRIZADOS,
    COORDENADORES,
	ADMINISTRADORES;
    
}

//ADMINISTRADORES("ADMINISTRADORES"),
//PROFESSORES("PROFESSORES"),
//TECNICOS("TECNICOS"),
//MATEMATICA("MATEMATICA"),
//LETRAS("LETRAS"),
//CONTABEIS("CONTABEIS"),
//CPD("CPD"),
//BIBLIOTECA("BIBLIOTECA"),
//TERCEIRIZADOS("TERCEIRIZADOS"),
//COORDENADORES("COORDENADORES"),
//DIRECAO("DIRECAO");
