INSERT INTO usuario  VALUES (1,'123','01404526480');
INSERT INTO grupo VALUES (1,'ADMINISTRADORES'),(2,'SECRETARIAS'),(3,'COORDENADORES'),(4,'BIBLIOTECA'),(5,'DIRECAO');
INSERT INTO usuario_grupo VALUES (1,1)
-- select setval('', 1);